name = "Empirikos"
uuid = "cab608d6-c565-4ea1-96d6-ce5441ba21b0"
authors = ["Nikos Ignatiadis <nikos.ignatiadis01@gmail.com> and contributors"]
version = "0.6.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearFractional = "31851ddc-f9b7-5097-a470-69ef907d7682"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
ParameterJuMP = "774612a8-9878-5177-865a-ca53ae2495f9"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RangeHelpers = "3a07dd3d-1c52-4395-8858-40c6328157db"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsDiscretizations = "1d0cfea5-fabc-4e25-85a8-945fa8abc3c9"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
CSV = "0.8, 0.9, 0.10"
DataStructures = "0.17,0.18"
Distributions = "0.24.7, 0.25"
JuMP = "^1"
KernelDensity = "0.6"
LinearAlgebra = "1.9"
LinearFractional = "^0.7.8"
LogExpFunctions = "0.3"
MathOptInterface = "^1"
MultipleTesting = "0.6"
ParameterJuMP = "^0.4"
QuadGK = "2.0"
Random = "1.9"
RangeHelpers = "0.1.9"
RecipesBase = "1.2, 1.3"
Setfield = "1"
SpecialFunctions = "2"
Statistics = "1.9"
StatsBase = "0.33, 0.34"
StatsDiscretizations = "0.2"
UnPack = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
